# Reference file for fields:
# https://github.com/szymonmaszke/torchlambda/wiki/YAML-settings-file-reference
---
grad: False
validate_json: true
data: data
validate_data: true
model: /opt/model.ptc
inputs: [1, 3, width, height]
validate_inputs: true
cast: float
divide: 255
normalize:
  means: [0.485, 0.456, 0.406]
  stddevs: [0.229, 0.224, 0.225]
return:
  output:
    type: double
    name: output
    item: false
  result:
    type: int
    name: result
    operations: argmax
    arguments: 1
    item: true
